spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orm_platform
    username: orm_user
    password: orm_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # вывод SQL в лог
    properties:
      hibernate:
        format_sql: true # форматирование SQL для удобства чтения

server:
  port: 8080

