spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orm_platform
    username: orm_user
    password: orm_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
